# No endpoint or credential is generated by Nix; both are read at runtime.
{ pkgs, ... }:
let
  client = ./kaggle-llm/client.py;
  helper = name: action: pkgs.writeShellApplication {
    inherit name;
    runtimeInputs = [ pkgs.python3 pkgs.claude-code pkgs.pass ];
    text = ''exec python3 ${client} ${action} "$@"'';
  };
in {
  home.packages = [
    (helper "kaggle-code" "code")
    (helper "kaggle-code-status" "status")
  ];
}
