{ config, lib, pkgs, ... }:

# The animated wallpaper.
#
# swaybg can only draw a still, so the sway config keeps a still as every
# output's background and mpvpaper layers a video over the one output that has
# one. Frame 0 of the video is that same still, so the handover is invisible.
#
# ConditionPathExists is what makes this safe to define for every Linux machine:
# where the video is absent the unit is skipped rather than failed, and the
# still wallpaper is simply what stays on screen. The same holds if mpvpaper
# dies — the background underneath it is already correct.
#
# The video is regenerated by wallpaper/ in the repo root and installed to
# ~/.local/share by its install.sh. It deliberately lives outside the flake: it
# is a large binary that would bloat every clone, and it composites third-party
# footage whose licence permits derivative works but not redistribution.

let
  animatedWallpaper = "${config.xdg.dataHome}/wallpaper/animated.mp4";
in {
  options.wallpaper.animatedOutput = lib.mkOption {
    type = lib.types.str;
    default = "*";
    example = "DP-1";
    description = ''
      Sway output to draw the animated wallpaper on.

      mpvpaper covers whatever outputs it is given and "*" means all of them, so
      on a multi-monitor machine the default paints the video across every
      screen — including screens whose aspect ratio it was never composed for,
      and over the different still those screens were given. Name a single
      output there instead.
    '';
  };

  config.systemd.user.services.mpvpaper = {
    Unit = {
      Description = "Animated wallpaper";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
      ConditionPathExists = animatedWallpaper;
    };
    Service = {
      # -p pauses decoding whenever the wallpaper is fully covered, which is
      # most of the time in practice. Running uncovered it costs ~5% of one core.
      ExecStart = lib.concatStringsSep " " [
        "${pkgs.mpvpaper}/bin/mpvpaper"
        "-p"
        "-o '--loop-file=inf --no-audio --hwdec=auto --video-unscaled=no --really-quiet'"
        "'${config.wallpaper.animatedOutput}'"
        animatedWallpaper
      ];
      Restart = "on-failure";
      RestartSec = 5;
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
